// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package edu.ucf.student.jdavies.cnt5008.proto;

public interface BeaconOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Beacon)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.HostId hostId = 1;</code>
   */
  boolean hasHostId();
  /**
   * <code>.proto.HostId hostId = 1;</code>
   */
  edu.ucf.student.jdavies.cnt5008.proto.HostId getHostId();
  /**
   * <code>.proto.HostId hostId = 1;</code>
   */
  edu.ucf.student.jdavies.cnt5008.proto.HostIdOrBuilder getHostIdOrBuilder();

  /**
   * <code>.proto.Beacon.Status status = 2;</code>
   */
  int getStatusValue();
  /**
   * <code>.proto.Beacon.Status status = 2;</code>
   */
  edu.ucf.student.jdavies.cnt5008.proto.Beacon.Status getStatus();
}
