// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package edu.ucf.student.jdavies.cnt5008.proto;

/**
 * Protobuf type {@code proto.Beacon}
 */
public  final class Beacon extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.Beacon)
    BeaconOrBuilder {
  // Use Beacon.newBuilder() to construct.
  private Beacon(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Beacon() {
    status_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Beacon(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            edu.ucf.student.jdavies.cnt5008.proto.HostId.Builder subBuilder = null;
            if (hostId_ != null) {
              subBuilder = hostId_.toBuilder();
            }
            hostId_ = input.readMessage(edu.ucf.student.jdavies.cnt5008.proto.HostId.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(hostId_);
              hostId_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.ucf.student.jdavies.cnt5008.proto.Proto.internal_static_proto_Beacon_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.ucf.student.jdavies.cnt5008.proto.Proto.internal_static_proto_Beacon_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.ucf.student.jdavies.cnt5008.proto.Beacon.class, edu.ucf.student.jdavies.cnt5008.proto.Beacon.Builder.class);
  }

  /**
   * Protobuf enum {@code proto.Beacon.Status}
   */
  public enum Status
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PRESENT = 0;</code>
     */
    PRESENT(0),
    /**
     * <code>GONE = 1;</code>
     */
    GONE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PRESENT = 0;</code>
     */
    public static final int PRESENT_VALUE = 0;
    /**
     * <code>GONE = 1;</code>
     */
    public static final int GONE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Status valueOf(int value) {
      return forNumber(value);
    }

    public static Status forNumber(int value) {
      switch (value) {
        case 0: return PRESENT;
        case 1: return GONE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Status> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            public Status findValueByNumber(int number) {
              return Status.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return edu.ucf.student.jdavies.cnt5008.proto.Beacon.getDescriptor().getEnumTypes().get(0);
    }

    private static final Status[] VALUES = values();

    public static Status valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Status(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.Beacon.Status)
  }

  public static final int HOSTID_FIELD_NUMBER = 1;
  private edu.ucf.student.jdavies.cnt5008.proto.HostId hostId_;
  /**
   * <code>.proto.HostId hostId = 1;</code>
   */
  public boolean hasHostId() {
    return hostId_ != null;
  }
  /**
   * <code>.proto.HostId hostId = 1;</code>
   */
  public edu.ucf.student.jdavies.cnt5008.proto.HostId getHostId() {
    return hostId_ == null ? edu.ucf.student.jdavies.cnt5008.proto.HostId.getDefaultInstance() : hostId_;
  }
  /**
   * <code>.proto.HostId hostId = 1;</code>
   */
  public edu.ucf.student.jdavies.cnt5008.proto.HostIdOrBuilder getHostIdOrBuilder() {
    return getHostId();
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private int status_;
  /**
   * <code>.proto.Beacon.Status status = 2;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.proto.Beacon.Status status = 2;</code>
   */
  public edu.ucf.student.jdavies.cnt5008.proto.Beacon.Status getStatus() {
    edu.ucf.student.jdavies.cnt5008.proto.Beacon.Status result = edu.ucf.student.jdavies.cnt5008.proto.Beacon.Status.valueOf(status_);
    return result == null ? edu.ucf.student.jdavies.cnt5008.proto.Beacon.Status.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (hostId_ != null) {
      output.writeMessage(1, getHostId());
    }
    if (status_ != edu.ucf.student.jdavies.cnt5008.proto.Beacon.Status.PRESENT.getNumber()) {
      output.writeEnum(2, status_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (hostId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHostId());
    }
    if (status_ != edu.ucf.student.jdavies.cnt5008.proto.Beacon.Status.PRESENT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, status_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof edu.ucf.student.jdavies.cnt5008.proto.Beacon)) {
      return super.equals(obj);
    }
    edu.ucf.student.jdavies.cnt5008.proto.Beacon other = (edu.ucf.student.jdavies.cnt5008.proto.Beacon) obj;

    boolean result = true;
    result = result && (hasHostId() == other.hasHostId());
    if (hasHostId()) {
      result = result && getHostId()
          .equals(other.getHostId());
    }
    result = result && status_ == other.status_;
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHostId()) {
      hash = (37 * hash) + HOSTID_FIELD_NUMBER;
      hash = (53 * hash) + getHostId().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static edu.ucf.student.jdavies.cnt5008.proto.Beacon parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Beacon parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Beacon parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Beacon parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Beacon parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Beacon parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Beacon parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Beacon parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Beacon parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Beacon parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Beacon parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Beacon parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.ucf.student.jdavies.cnt5008.proto.Beacon prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.Beacon}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.Beacon)
      edu.ucf.student.jdavies.cnt5008.proto.BeaconOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.ucf.student.jdavies.cnt5008.proto.Proto.internal_static_proto_Beacon_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.ucf.student.jdavies.cnt5008.proto.Proto.internal_static_proto_Beacon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.ucf.student.jdavies.cnt5008.proto.Beacon.class, edu.ucf.student.jdavies.cnt5008.proto.Beacon.Builder.class);
    }

    // Construct using edu.ucf.student.jdavies.cnt5008.proto.Beacon.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (hostIdBuilder_ == null) {
        hostId_ = null;
      } else {
        hostId_ = null;
        hostIdBuilder_ = null;
      }
      status_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.ucf.student.jdavies.cnt5008.proto.Proto.internal_static_proto_Beacon_descriptor;
    }

    public edu.ucf.student.jdavies.cnt5008.proto.Beacon getDefaultInstanceForType() {
      return edu.ucf.student.jdavies.cnt5008.proto.Beacon.getDefaultInstance();
    }

    public edu.ucf.student.jdavies.cnt5008.proto.Beacon build() {
      edu.ucf.student.jdavies.cnt5008.proto.Beacon result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public edu.ucf.student.jdavies.cnt5008.proto.Beacon buildPartial() {
      edu.ucf.student.jdavies.cnt5008.proto.Beacon result = new edu.ucf.student.jdavies.cnt5008.proto.Beacon(this);
      if (hostIdBuilder_ == null) {
        result.hostId_ = hostId_;
      } else {
        result.hostId_ = hostIdBuilder_.build();
      }
      result.status_ = status_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof edu.ucf.student.jdavies.cnt5008.proto.Beacon) {
        return mergeFrom((edu.ucf.student.jdavies.cnt5008.proto.Beacon)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(edu.ucf.student.jdavies.cnt5008.proto.Beacon other) {
      if (other == edu.ucf.student.jdavies.cnt5008.proto.Beacon.getDefaultInstance()) return this;
      if (other.hasHostId()) {
        mergeHostId(other.getHostId());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      edu.ucf.student.jdavies.cnt5008.proto.Beacon parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (edu.ucf.student.jdavies.cnt5008.proto.Beacon) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private edu.ucf.student.jdavies.cnt5008.proto.HostId hostId_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        edu.ucf.student.jdavies.cnt5008.proto.HostId, edu.ucf.student.jdavies.cnt5008.proto.HostId.Builder, edu.ucf.student.jdavies.cnt5008.proto.HostIdOrBuilder> hostIdBuilder_;
    /**
     * <code>.proto.HostId hostId = 1;</code>
     */
    public boolean hasHostId() {
      return hostIdBuilder_ != null || hostId_ != null;
    }
    /**
     * <code>.proto.HostId hostId = 1;</code>
     */
    public edu.ucf.student.jdavies.cnt5008.proto.HostId getHostId() {
      if (hostIdBuilder_ == null) {
        return hostId_ == null ? edu.ucf.student.jdavies.cnt5008.proto.HostId.getDefaultInstance() : hostId_;
      } else {
        return hostIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.HostId hostId = 1;</code>
     */
    public Builder setHostId(edu.ucf.student.jdavies.cnt5008.proto.HostId value) {
      if (hostIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        hostId_ = value;
        onChanged();
      } else {
        hostIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.proto.HostId hostId = 1;</code>
     */
    public Builder setHostId(
        edu.ucf.student.jdavies.cnt5008.proto.HostId.Builder builderForValue) {
      if (hostIdBuilder_ == null) {
        hostId_ = builderForValue.build();
        onChanged();
      } else {
        hostIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.proto.HostId hostId = 1;</code>
     */
    public Builder mergeHostId(edu.ucf.student.jdavies.cnt5008.proto.HostId value) {
      if (hostIdBuilder_ == null) {
        if (hostId_ != null) {
          hostId_ =
            edu.ucf.student.jdavies.cnt5008.proto.HostId.newBuilder(hostId_).mergeFrom(value).buildPartial();
        } else {
          hostId_ = value;
        }
        onChanged();
      } else {
        hostIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.proto.HostId hostId = 1;</code>
     */
    public Builder clearHostId() {
      if (hostIdBuilder_ == null) {
        hostId_ = null;
        onChanged();
      } else {
        hostId_ = null;
        hostIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.proto.HostId hostId = 1;</code>
     */
    public edu.ucf.student.jdavies.cnt5008.proto.HostId.Builder getHostIdBuilder() {
      
      onChanged();
      return getHostIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.HostId hostId = 1;</code>
     */
    public edu.ucf.student.jdavies.cnt5008.proto.HostIdOrBuilder getHostIdOrBuilder() {
      if (hostIdBuilder_ != null) {
        return hostIdBuilder_.getMessageOrBuilder();
      } else {
        return hostId_ == null ?
            edu.ucf.student.jdavies.cnt5008.proto.HostId.getDefaultInstance() : hostId_;
      }
    }
    /**
     * <code>.proto.HostId hostId = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        edu.ucf.student.jdavies.cnt5008.proto.HostId, edu.ucf.student.jdavies.cnt5008.proto.HostId.Builder, edu.ucf.student.jdavies.cnt5008.proto.HostIdOrBuilder> 
        getHostIdFieldBuilder() {
      if (hostIdBuilder_ == null) {
        hostIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            edu.ucf.student.jdavies.cnt5008.proto.HostId, edu.ucf.student.jdavies.cnt5008.proto.HostId.Builder, edu.ucf.student.jdavies.cnt5008.proto.HostIdOrBuilder>(
                getHostId(),
                getParentForChildren(),
                isClean());
        hostId_ = null;
      }
      return hostIdBuilder_;
    }

    private int status_ = 0;
    /**
     * <code>.proto.Beacon.Status status = 2;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.proto.Beacon.Status status = 2;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.Beacon.Status status = 2;</code>
     */
    public edu.ucf.student.jdavies.cnt5008.proto.Beacon.Status getStatus() {
      edu.ucf.student.jdavies.cnt5008.proto.Beacon.Status result = edu.ucf.student.jdavies.cnt5008.proto.Beacon.Status.valueOf(status_);
      return result == null ? edu.ucf.student.jdavies.cnt5008.proto.Beacon.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.proto.Beacon.Status status = 2;</code>
     */
    public Builder setStatus(edu.ucf.student.jdavies.cnt5008.proto.Beacon.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.proto.Beacon.Status status = 2;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:proto.Beacon)
  }

  // @@protoc_insertion_point(class_scope:proto.Beacon)
  private static final edu.ucf.student.jdavies.cnt5008.proto.Beacon DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.ucf.student.jdavies.cnt5008.proto.Beacon();
  }

  public static edu.ucf.student.jdavies.cnt5008.proto.Beacon getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Beacon>
      PARSER = new com.google.protobuf.AbstractParser<Beacon>() {
    public Beacon parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Beacon(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Beacon> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Beacon> getParserForType() {
    return PARSER;
  }

  public edu.ucf.student.jdavies.cnt5008.proto.Beacon getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

