// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package edu.ucf.student.jdavies.cnt5008.proto;

public interface HeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Header)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.Header.Mode mode = 1;</code>
   */
  int getModeValue();
  /**
   * <code>.proto.Header.Mode mode = 1;</code>
   */
  edu.ucf.student.jdavies.cnt5008.proto.Header.Mode getMode();

  /**
   * <code>int32 sequence = 2;</code>
   */
  int getSequence();
}
