// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package edu.ucf.student.jdavies.cnt5008.proto;

public interface HostIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.HostId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ip = 1;</code>
   */
  int getIp();

  /**
   * <code>int32 port = 2;</code>
   */
  int getPort();
}
