// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package edu.ucf.student.jdavies.cnt5008.proto;

/**
 * Protobuf type {@code proto.Message}
 */
public  final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.Message)
    MessageOrBuilder {
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    payload_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            edu.ucf.student.jdavies.cnt5008.proto.HostId.Builder subBuilder = null;
            if (source_ != null) {
              subBuilder = source_.toBuilder();
            }
            source_ = input.readMessage(edu.ucf.student.jdavies.cnt5008.proto.HostId.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(source_);
              source_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            edu.ucf.student.jdavies.cnt5008.proto.Header.Builder subBuilder = null;
            if (header_ != null) {
              subBuilder = header_.toBuilder();
            }
            header_ = input.readMessage(edu.ucf.student.jdavies.cnt5008.proto.Header.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(header_);
              header_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {

            payload_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.ucf.student.jdavies.cnt5008.proto.Proto.internal_static_proto_Message_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.ucf.student.jdavies.cnt5008.proto.Proto.internal_static_proto_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.ucf.student.jdavies.cnt5008.proto.Message.class, edu.ucf.student.jdavies.cnt5008.proto.Message.Builder.class);
  }

  public static final int SOURCE_FIELD_NUMBER = 1;
  private edu.ucf.student.jdavies.cnt5008.proto.HostId source_;
  /**
   * <code>.proto.HostId source = 1;</code>
   */
  public boolean hasSource() {
    return source_ != null;
  }
  /**
   * <code>.proto.HostId source = 1;</code>
   */
  public edu.ucf.student.jdavies.cnt5008.proto.HostId getSource() {
    return source_ == null ? edu.ucf.student.jdavies.cnt5008.proto.HostId.getDefaultInstance() : source_;
  }
  /**
   * <code>.proto.HostId source = 1;</code>
   */
  public edu.ucf.student.jdavies.cnt5008.proto.HostIdOrBuilder getSourceOrBuilder() {
    return getSource();
  }

  public static final int HEADER_FIELD_NUMBER = 2;
  private edu.ucf.student.jdavies.cnt5008.proto.Header header_;
  /**
   * <code>.proto.Header header = 2;</code>
   */
  public boolean hasHeader() {
    return header_ != null;
  }
  /**
   * <code>.proto.Header header = 2;</code>
   */
  public edu.ucf.student.jdavies.cnt5008.proto.Header getHeader() {
    return header_ == null ? edu.ucf.student.jdavies.cnt5008.proto.Header.getDefaultInstance() : header_;
  }
  /**
   * <code>.proto.Header header = 2;</code>
   */
  public edu.ucf.student.jdavies.cnt5008.proto.HeaderOrBuilder getHeaderOrBuilder() {
    return getHeader();
  }

  public static final int PAYLOAD_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString payload_;
  /**
   * <code>bytes payload = 3;</code>
   */
  public com.google.protobuf.ByteString getPayload() {
    return payload_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (source_ != null) {
      output.writeMessage(1, getSource());
    }
    if (header_ != null) {
      output.writeMessage(2, getHeader());
    }
    if (!payload_.isEmpty()) {
      output.writeBytes(3, payload_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (source_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSource());
    }
    if (header_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getHeader());
    }
    if (!payload_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, payload_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof edu.ucf.student.jdavies.cnt5008.proto.Message)) {
      return super.equals(obj);
    }
    edu.ucf.student.jdavies.cnt5008.proto.Message other = (edu.ucf.student.jdavies.cnt5008.proto.Message) obj;

    boolean result = true;
    result = result && (hasSource() == other.hasSource());
    if (hasSource()) {
      result = result && getSource()
          .equals(other.getSource());
    }
    result = result && (hasHeader() == other.hasHeader());
    if (hasHeader()) {
      result = result && getHeader()
          .equals(other.getHeader());
    }
    result = result && getPayload()
        .equals(other.getPayload());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSource()) {
      hash = (37 * hash) + SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getSource().hashCode();
    }
    if (hasHeader()) {
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getHeader().hashCode();
    }
    hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getPayload().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static edu.ucf.student.jdavies.cnt5008.proto.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.ucf.student.jdavies.cnt5008.proto.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.Message)
      edu.ucf.student.jdavies.cnt5008.proto.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.ucf.student.jdavies.cnt5008.proto.Proto.internal_static_proto_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.ucf.student.jdavies.cnt5008.proto.Proto.internal_static_proto_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.ucf.student.jdavies.cnt5008.proto.Message.class, edu.ucf.student.jdavies.cnt5008.proto.Message.Builder.class);
    }

    // Construct using edu.ucf.student.jdavies.cnt5008.proto.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (sourceBuilder_ == null) {
        source_ = null;
      } else {
        source_ = null;
        sourceBuilder_ = null;
      }
      if (headerBuilder_ == null) {
        header_ = null;
      } else {
        header_ = null;
        headerBuilder_ = null;
      }
      payload_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.ucf.student.jdavies.cnt5008.proto.Proto.internal_static_proto_Message_descriptor;
    }

    public edu.ucf.student.jdavies.cnt5008.proto.Message getDefaultInstanceForType() {
      return edu.ucf.student.jdavies.cnt5008.proto.Message.getDefaultInstance();
    }

    public edu.ucf.student.jdavies.cnt5008.proto.Message build() {
      edu.ucf.student.jdavies.cnt5008.proto.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public edu.ucf.student.jdavies.cnt5008.proto.Message buildPartial() {
      edu.ucf.student.jdavies.cnt5008.proto.Message result = new edu.ucf.student.jdavies.cnt5008.proto.Message(this);
      if (sourceBuilder_ == null) {
        result.source_ = source_;
      } else {
        result.source_ = sourceBuilder_.build();
      }
      if (headerBuilder_ == null) {
        result.header_ = header_;
      } else {
        result.header_ = headerBuilder_.build();
      }
      result.payload_ = payload_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof edu.ucf.student.jdavies.cnt5008.proto.Message) {
        return mergeFrom((edu.ucf.student.jdavies.cnt5008.proto.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(edu.ucf.student.jdavies.cnt5008.proto.Message other) {
      if (other == edu.ucf.student.jdavies.cnt5008.proto.Message.getDefaultInstance()) return this;
      if (other.hasSource()) {
        mergeSource(other.getSource());
      }
      if (other.hasHeader()) {
        mergeHeader(other.getHeader());
      }
      if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
        setPayload(other.getPayload());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      edu.ucf.student.jdavies.cnt5008.proto.Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (edu.ucf.student.jdavies.cnt5008.proto.Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private edu.ucf.student.jdavies.cnt5008.proto.HostId source_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        edu.ucf.student.jdavies.cnt5008.proto.HostId, edu.ucf.student.jdavies.cnt5008.proto.HostId.Builder, edu.ucf.student.jdavies.cnt5008.proto.HostIdOrBuilder> sourceBuilder_;
    /**
     * <code>.proto.HostId source = 1;</code>
     */
    public boolean hasSource() {
      return sourceBuilder_ != null || source_ != null;
    }
    /**
     * <code>.proto.HostId source = 1;</code>
     */
    public edu.ucf.student.jdavies.cnt5008.proto.HostId getSource() {
      if (sourceBuilder_ == null) {
        return source_ == null ? edu.ucf.student.jdavies.cnt5008.proto.HostId.getDefaultInstance() : source_;
      } else {
        return sourceBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.HostId source = 1;</code>
     */
    public Builder setSource(edu.ucf.student.jdavies.cnt5008.proto.HostId value) {
      if (sourceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        source_ = value;
        onChanged();
      } else {
        sourceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.proto.HostId source = 1;</code>
     */
    public Builder setSource(
        edu.ucf.student.jdavies.cnt5008.proto.HostId.Builder builderForValue) {
      if (sourceBuilder_ == null) {
        source_ = builderForValue.build();
        onChanged();
      } else {
        sourceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.proto.HostId source = 1;</code>
     */
    public Builder mergeSource(edu.ucf.student.jdavies.cnt5008.proto.HostId value) {
      if (sourceBuilder_ == null) {
        if (source_ != null) {
          source_ =
            edu.ucf.student.jdavies.cnt5008.proto.HostId.newBuilder(source_).mergeFrom(value).buildPartial();
        } else {
          source_ = value;
        }
        onChanged();
      } else {
        sourceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.proto.HostId source = 1;</code>
     */
    public Builder clearSource() {
      if (sourceBuilder_ == null) {
        source_ = null;
        onChanged();
      } else {
        source_ = null;
        sourceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.proto.HostId source = 1;</code>
     */
    public edu.ucf.student.jdavies.cnt5008.proto.HostId.Builder getSourceBuilder() {
      
      onChanged();
      return getSourceFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.HostId source = 1;</code>
     */
    public edu.ucf.student.jdavies.cnt5008.proto.HostIdOrBuilder getSourceOrBuilder() {
      if (sourceBuilder_ != null) {
        return sourceBuilder_.getMessageOrBuilder();
      } else {
        return source_ == null ?
            edu.ucf.student.jdavies.cnt5008.proto.HostId.getDefaultInstance() : source_;
      }
    }
    /**
     * <code>.proto.HostId source = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        edu.ucf.student.jdavies.cnt5008.proto.HostId, edu.ucf.student.jdavies.cnt5008.proto.HostId.Builder, edu.ucf.student.jdavies.cnt5008.proto.HostIdOrBuilder> 
        getSourceFieldBuilder() {
      if (sourceBuilder_ == null) {
        sourceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            edu.ucf.student.jdavies.cnt5008.proto.HostId, edu.ucf.student.jdavies.cnt5008.proto.HostId.Builder, edu.ucf.student.jdavies.cnt5008.proto.HostIdOrBuilder>(
                getSource(),
                getParentForChildren(),
                isClean());
        source_ = null;
      }
      return sourceBuilder_;
    }

    private edu.ucf.student.jdavies.cnt5008.proto.Header header_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        edu.ucf.student.jdavies.cnt5008.proto.Header, edu.ucf.student.jdavies.cnt5008.proto.Header.Builder, edu.ucf.student.jdavies.cnt5008.proto.HeaderOrBuilder> headerBuilder_;
    /**
     * <code>.proto.Header header = 2;</code>
     */
    public boolean hasHeader() {
      return headerBuilder_ != null || header_ != null;
    }
    /**
     * <code>.proto.Header header = 2;</code>
     */
    public edu.ucf.student.jdavies.cnt5008.proto.Header getHeader() {
      if (headerBuilder_ == null) {
        return header_ == null ? edu.ucf.student.jdavies.cnt5008.proto.Header.getDefaultInstance() : header_;
      } else {
        return headerBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.Header header = 2;</code>
     */
    public Builder setHeader(edu.ucf.student.jdavies.cnt5008.proto.Header value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        header_ = value;
        onChanged();
      } else {
        headerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.proto.Header header = 2;</code>
     */
    public Builder setHeader(
        edu.ucf.student.jdavies.cnt5008.proto.Header.Builder builderForValue) {
      if (headerBuilder_ == null) {
        header_ = builderForValue.build();
        onChanged();
      } else {
        headerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.proto.Header header = 2;</code>
     */
    public Builder mergeHeader(edu.ucf.student.jdavies.cnt5008.proto.Header value) {
      if (headerBuilder_ == null) {
        if (header_ != null) {
          header_ =
            edu.ucf.student.jdavies.cnt5008.proto.Header.newBuilder(header_).mergeFrom(value).buildPartial();
        } else {
          header_ = value;
        }
        onChanged();
      } else {
        headerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.proto.Header header = 2;</code>
     */
    public Builder clearHeader() {
      if (headerBuilder_ == null) {
        header_ = null;
        onChanged();
      } else {
        header_ = null;
        headerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.proto.Header header = 2;</code>
     */
    public edu.ucf.student.jdavies.cnt5008.proto.Header.Builder getHeaderBuilder() {
      
      onChanged();
      return getHeaderFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.Header header = 2;</code>
     */
    public edu.ucf.student.jdavies.cnt5008.proto.HeaderOrBuilder getHeaderOrBuilder() {
      if (headerBuilder_ != null) {
        return headerBuilder_.getMessageOrBuilder();
      } else {
        return header_ == null ?
            edu.ucf.student.jdavies.cnt5008.proto.Header.getDefaultInstance() : header_;
      }
    }
    /**
     * <code>.proto.Header header = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        edu.ucf.student.jdavies.cnt5008.proto.Header, edu.ucf.student.jdavies.cnt5008.proto.Header.Builder, edu.ucf.student.jdavies.cnt5008.proto.HeaderOrBuilder> 
        getHeaderFieldBuilder() {
      if (headerBuilder_ == null) {
        headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            edu.ucf.student.jdavies.cnt5008.proto.Header, edu.ucf.student.jdavies.cnt5008.proto.Header.Builder, edu.ucf.student.jdavies.cnt5008.proto.HeaderOrBuilder>(
                getHeader(),
                getParentForChildren(),
                isClean());
        header_ = null;
      }
      return headerBuilder_;
    }

    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes payload = 3;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }
    /**
     * <code>bytes payload = 3;</code>
     */
    public Builder setPayload(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      payload_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes payload = 3;</code>
     */
    public Builder clearPayload() {
      
      payload_ = getDefaultInstance().getPayload();
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:proto.Message)
  }

  // @@protoc_insertion_point(class_scope:proto.Message)
  private static final edu.ucf.student.jdavies.cnt5008.proto.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.ucf.student.jdavies.cnt5008.proto.Message();
  }

  public static edu.ucf.student.jdavies.cnt5008.proto.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  public edu.ucf.student.jdavies.cnt5008.proto.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

