// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package edu.ucf.student.jdavies.cnt5008.proto;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.HostId source = 1;</code>
   */
  boolean hasSource();
  /**
   * <code>.proto.HostId source = 1;</code>
   */
  edu.ucf.student.jdavies.cnt5008.proto.HostId getSource();
  /**
   * <code>.proto.HostId source = 1;</code>
   */
  edu.ucf.student.jdavies.cnt5008.proto.HostIdOrBuilder getSourceOrBuilder();

  /**
   * <code>.proto.Header header = 2;</code>
   */
  boolean hasHeader();
  /**
   * <code>.proto.Header header = 2;</code>
   */
  edu.ucf.student.jdavies.cnt5008.proto.Header getHeader();
  /**
   * <code>.proto.Header header = 2;</code>
   */
  edu.ucf.student.jdavies.cnt5008.proto.HeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>bytes payload = 3;</code>
   */
  com.google.protobuf.ByteString getPayload();
}
