// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package edu.ucf.student.jdavies.cnt5008.proto;

public final class Proto {
  private Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016messages.proto\022\005proto\"\271\001\n\007Message\022\020\n\010r" +
      "eliable\030\001 \001(\010\022\020\n\010response\030\002 \001(\010\022\020\n\010seque" +
      "nce\030\003 \001(\005\022\025\n\rsenderAddress\030\004 \001(\005\022\022\n\nsend" +
      "erPort\030\005 \001(\005\022!\n\004mode\030\006 \001(\0162\023.proto.Messa" +
      "ge.Mode\022\017\n\007payload\030\010 \001(\014\"\031\n\004Mode\022\007\n\003ACK\020" +
      "\000\022\010\n\004NACK\020\001B0\n%edu.ucf.student.jdavies.c" +
      "nt5008.protoB\005ProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Message_descriptor,
        new java.lang.String[] { "Reliable", "Response", "Sequence", "SenderAddress", "SenderPort", "Mode", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
