// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package edu.ucf.student.jdavies.cnt5008.proto;

public final class Proto {
  private Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool reliable = 1;</code>
     */
    boolean getReliable();

    /**
     * <code>.proto.Message.Mode mode = 2;</code>
     */
    int getModeValue();
    /**
     * <code>.proto.Message.Mode mode = 2;</code>
     */
    edu.ucf.student.jdavies.cnt5008.proto.Proto.Message.Mode getMode();

    /**
     * <code>uint32 sequence = 3;</code>
     */
    int getSequence();

    /**
     * <code>bytes payload = 4;</code>
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code proto.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      reliable_ = false;
      mode_ = 0;
      sequence_ = 0;
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              reliable_ = input.readBool();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              mode_ = rawValue;
              break;
            }
            case 24: {

              sequence_ = input.readUInt32();
              break;
            }
            case 34: {

              payload_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.ucf.student.jdavies.cnt5008.proto.Proto.internal_static_proto_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.ucf.student.jdavies.cnt5008.proto.Proto.internal_static_proto_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.ucf.student.jdavies.cnt5008.proto.Proto.Message.class, edu.ucf.student.jdavies.cnt5008.proto.Proto.Message.Builder.class);
    }

    /**
     * Protobuf enum {@code proto.Message.Mode}
     */
    public enum Mode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ACK = 0;</code>
       */
      ACK(0),
      /**
       * <code>NACK = 1;</code>
       */
      NACK(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ACK = 0;</code>
       */
      public static final int ACK_VALUE = 0;
      /**
       * <code>NACK = 1;</code>
       */
      public static final int NACK_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Mode valueOf(int value) {
        return forNumber(value);
      }

      public static Mode forNumber(int value) {
        switch (value) {
          case 0: return ACK;
          case 1: return NACK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Mode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Mode> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Mode>() {
              public Mode findValueByNumber(int number) {
                return Mode.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return edu.ucf.student.jdavies.cnt5008.proto.Proto.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final Mode[] VALUES = values();

      public static Mode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Mode(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto.Message.Mode)
    }

    public static final int RELIABLE_FIELD_NUMBER = 1;
    private boolean reliable_;
    /**
     * <code>bool reliable = 1;</code>
     */
    public boolean getReliable() {
      return reliable_;
    }

    public static final int MODE_FIELD_NUMBER = 2;
    private int mode_;
    /**
     * <code>.proto.Message.Mode mode = 2;</code>
     */
    public int getModeValue() {
      return mode_;
    }
    /**
     * <code>.proto.Message.Mode mode = 2;</code>
     */
    public edu.ucf.student.jdavies.cnt5008.proto.Proto.Message.Mode getMode() {
      edu.ucf.student.jdavies.cnt5008.proto.Proto.Message.Mode result = edu.ucf.student.jdavies.cnt5008.proto.Proto.Message.Mode.valueOf(mode_);
      return result == null ? edu.ucf.student.jdavies.cnt5008.proto.Proto.Message.Mode.UNRECOGNIZED : result;
    }

    public static final int SEQUENCE_FIELD_NUMBER = 3;
    private int sequence_;
    /**
     * <code>uint32 sequence = 3;</code>
     */
    public int getSequence() {
      return sequence_;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>bytes payload = 4;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (reliable_ != false) {
        output.writeBool(1, reliable_);
      }
      if (mode_ != edu.ucf.student.jdavies.cnt5008.proto.Proto.Message.Mode.ACK.getNumber()) {
        output.writeEnum(2, mode_);
      }
      if (sequence_ != 0) {
        output.writeUInt32(3, sequence_);
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(4, payload_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (reliable_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, reliable_);
      }
      if (mode_ != edu.ucf.student.jdavies.cnt5008.proto.Proto.Message.Mode.ACK.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, mode_);
      }
      if (sequence_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, sequence_);
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, payload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.ucf.student.jdavies.cnt5008.proto.Proto.Message)) {
        return super.equals(obj);
      }
      edu.ucf.student.jdavies.cnt5008.proto.Proto.Message other = (edu.ucf.student.jdavies.cnt5008.proto.Proto.Message) obj;

      boolean result = true;
      result = result && (getReliable()
          == other.getReliable());
      result = result && mode_ == other.mode_;
      result = result && (getSequence()
          == other.getSequence());
      result = result && getPayload()
          .equals(other.getPayload());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RELIABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getReliable());
      hash = (37 * hash) + MODE_FIELD_NUMBER;
      hash = (53 * hash) + mode_;
      hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
      hash = (53 * hash) + getSequence();
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.ucf.student.jdavies.cnt5008.proto.Proto.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.ucf.student.jdavies.cnt5008.proto.Proto.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.ucf.student.jdavies.cnt5008.proto.Proto.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.ucf.student.jdavies.cnt5008.proto.Proto.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.ucf.student.jdavies.cnt5008.proto.Proto.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.ucf.student.jdavies.cnt5008.proto.Proto.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.ucf.student.jdavies.cnt5008.proto.Proto.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.ucf.student.jdavies.cnt5008.proto.Proto.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.ucf.student.jdavies.cnt5008.proto.Proto.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.ucf.student.jdavies.cnt5008.proto.Proto.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.ucf.student.jdavies.cnt5008.proto.Proto.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.ucf.student.jdavies.cnt5008.proto.Proto.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.ucf.student.jdavies.cnt5008.proto.Proto.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Message)
        edu.ucf.student.jdavies.cnt5008.proto.Proto.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.ucf.student.jdavies.cnt5008.proto.Proto.internal_static_proto_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.ucf.student.jdavies.cnt5008.proto.Proto.internal_static_proto_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.ucf.student.jdavies.cnt5008.proto.Proto.Message.class, edu.ucf.student.jdavies.cnt5008.proto.Proto.Message.Builder.class);
      }

      // Construct using edu.ucf.student.jdavies.cnt5008.proto.Proto.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        reliable_ = false;

        mode_ = 0;

        sequence_ = 0;

        payload_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.ucf.student.jdavies.cnt5008.proto.Proto.internal_static_proto_Message_descriptor;
      }

      public edu.ucf.student.jdavies.cnt5008.proto.Proto.Message getDefaultInstanceForType() {
        return edu.ucf.student.jdavies.cnt5008.proto.Proto.Message.getDefaultInstance();
      }

      public edu.ucf.student.jdavies.cnt5008.proto.Proto.Message build() {
        edu.ucf.student.jdavies.cnt5008.proto.Proto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.ucf.student.jdavies.cnt5008.proto.Proto.Message buildPartial() {
        edu.ucf.student.jdavies.cnt5008.proto.Proto.Message result = new edu.ucf.student.jdavies.cnt5008.proto.Proto.Message(this);
        result.reliable_ = reliable_;
        result.mode_ = mode_;
        result.sequence_ = sequence_;
        result.payload_ = payload_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.ucf.student.jdavies.cnt5008.proto.Proto.Message) {
          return mergeFrom((edu.ucf.student.jdavies.cnt5008.proto.Proto.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.ucf.student.jdavies.cnt5008.proto.Proto.Message other) {
        if (other == edu.ucf.student.jdavies.cnt5008.proto.Proto.Message.getDefaultInstance()) return this;
        if (other.getReliable() != false) {
          setReliable(other.getReliable());
        }
        if (other.mode_ != 0) {
          setModeValue(other.getModeValue());
        }
        if (other.getSequence() != 0) {
          setSequence(other.getSequence());
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.ucf.student.jdavies.cnt5008.proto.Proto.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.ucf.student.jdavies.cnt5008.proto.Proto.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean reliable_ ;
      /**
       * <code>bool reliable = 1;</code>
       */
      public boolean getReliable() {
        return reliable_;
      }
      /**
       * <code>bool reliable = 1;</code>
       */
      public Builder setReliable(boolean value) {
        
        reliable_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool reliable = 1;</code>
       */
      public Builder clearReliable() {
        
        reliable_ = false;
        onChanged();
        return this;
      }

      private int mode_ = 0;
      /**
       * <code>.proto.Message.Mode mode = 2;</code>
       */
      public int getModeValue() {
        return mode_;
      }
      /**
       * <code>.proto.Message.Mode mode = 2;</code>
       */
      public Builder setModeValue(int value) {
        mode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.proto.Message.Mode mode = 2;</code>
       */
      public edu.ucf.student.jdavies.cnt5008.proto.Proto.Message.Mode getMode() {
        edu.ucf.student.jdavies.cnt5008.proto.Proto.Message.Mode result = edu.ucf.student.jdavies.cnt5008.proto.Proto.Message.Mode.valueOf(mode_);
        return result == null ? edu.ucf.student.jdavies.cnt5008.proto.Proto.Message.Mode.UNRECOGNIZED : result;
      }
      /**
       * <code>.proto.Message.Mode mode = 2;</code>
       */
      public Builder setMode(edu.ucf.student.jdavies.cnt5008.proto.Proto.Message.Mode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        mode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.proto.Message.Mode mode = 2;</code>
       */
      public Builder clearMode() {
        
        mode_ = 0;
        onChanged();
        return this;
      }

      private int sequence_ ;
      /**
       * <code>uint32 sequence = 3;</code>
       */
      public int getSequence() {
        return sequence_;
      }
      /**
       * <code>uint32 sequence = 3;</code>
       */
      public Builder setSequence(int value) {
        
        sequence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 sequence = 3;</code>
       */
      public Builder clearSequence() {
        
        sequence_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes payload = 4;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>bytes payload = 4;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes payload = 4;</code>
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Message)
    }

    // @@protoc_insertion_point(class_scope:proto.Message)
    private static final edu.ucf.student.jdavies.cnt5008.proto.Proto.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.ucf.student.jdavies.cnt5008.proto.Proto.Message();
    }

    public static edu.ucf.student.jdavies.cnt5008.proto.Proto.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public edu.ucf.student.jdavies.cnt5008.proto.Proto.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016messages.proto\022\005proto\"|\n\007Message\022\020\n\010re" +
      "liable\030\001 \001(\010\022!\n\004mode\030\002 \001(\0162\023.proto.Messa" +
      "ge.Mode\022\020\n\010sequence\030\003 \001(\r\022\017\n\007payload\030\004 \001" +
      "(\014\"\031\n\004Mode\022\007\n\003ACK\020\000\022\010\n\004NACK\020\001B.\n%edu.ucf" +
      ".student.jdavies.cnt5008.protoB\005Protob\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Message_descriptor,
        new java.lang.String[] { "Reliable", "Mode", "Sequence", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
