// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package edu.ucf.student.jdavies.cnt5008.proto;

/**
 * Protobuf type {@code proto.Response}
 */
public  final class Response extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.Response)
    ResponseOrBuilder {
  // Use Response.newBuilder() to construct.
  private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Response() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Response(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            edu.ucf.student.jdavies.cnt5008.proto.HostId.Builder subBuilder = null;
            if (host_ != null) {
              subBuilder = host_.toBuilder();
            }
            host_ = input.readMessage(edu.ucf.student.jdavies.cnt5008.proto.HostId.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(host_);
              host_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.ucf.student.jdavies.cnt5008.proto.Proto.internal_static_proto_Response_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.ucf.student.jdavies.cnt5008.proto.Proto.internal_static_proto_Response_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.ucf.student.jdavies.cnt5008.proto.Response.class, edu.ucf.student.jdavies.cnt5008.proto.Response.Builder.class);
  }

  public static final int HOST_FIELD_NUMBER = 1;
  private edu.ucf.student.jdavies.cnt5008.proto.HostId host_;
  /**
   * <code>.proto.HostId host = 1;</code>
   */
  public boolean hasHost() {
    return host_ != null;
  }
  /**
   * <code>.proto.HostId host = 1;</code>
   */
  public edu.ucf.student.jdavies.cnt5008.proto.HostId getHost() {
    return host_ == null ? edu.ucf.student.jdavies.cnt5008.proto.HostId.getDefaultInstance() : host_;
  }
  /**
   * <code>.proto.HostId host = 1;</code>
   */
  public edu.ucf.student.jdavies.cnt5008.proto.HostIdOrBuilder getHostOrBuilder() {
    return getHost();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (host_ != null) {
      output.writeMessage(1, getHost());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (host_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHost());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof edu.ucf.student.jdavies.cnt5008.proto.Response)) {
      return super.equals(obj);
    }
    edu.ucf.student.jdavies.cnt5008.proto.Response other = (edu.ucf.student.jdavies.cnt5008.proto.Response) obj;

    boolean result = true;
    result = result && (hasHost() == other.hasHost());
    if (hasHost()) {
      result = result && getHost()
          .equals(other.getHost());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHost()) {
      hash = (37 * hash) + HOST_FIELD_NUMBER;
      hash = (53 * hash) + getHost().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static edu.ucf.student.jdavies.cnt5008.proto.Response parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Response parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Response parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Response parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Response parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Response parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Response parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Response parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Response parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Response parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Response parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.ucf.student.jdavies.cnt5008.proto.Response parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.ucf.student.jdavies.cnt5008.proto.Response prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.Response}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.Response)
      edu.ucf.student.jdavies.cnt5008.proto.ResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.ucf.student.jdavies.cnt5008.proto.Proto.internal_static_proto_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.ucf.student.jdavies.cnt5008.proto.Proto.internal_static_proto_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.ucf.student.jdavies.cnt5008.proto.Response.class, edu.ucf.student.jdavies.cnt5008.proto.Response.Builder.class);
    }

    // Construct using edu.ucf.student.jdavies.cnt5008.proto.Response.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (hostBuilder_ == null) {
        host_ = null;
      } else {
        host_ = null;
        hostBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.ucf.student.jdavies.cnt5008.proto.Proto.internal_static_proto_Response_descriptor;
    }

    public edu.ucf.student.jdavies.cnt5008.proto.Response getDefaultInstanceForType() {
      return edu.ucf.student.jdavies.cnt5008.proto.Response.getDefaultInstance();
    }

    public edu.ucf.student.jdavies.cnt5008.proto.Response build() {
      edu.ucf.student.jdavies.cnt5008.proto.Response result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public edu.ucf.student.jdavies.cnt5008.proto.Response buildPartial() {
      edu.ucf.student.jdavies.cnt5008.proto.Response result = new edu.ucf.student.jdavies.cnt5008.proto.Response(this);
      if (hostBuilder_ == null) {
        result.host_ = host_;
      } else {
        result.host_ = hostBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof edu.ucf.student.jdavies.cnt5008.proto.Response) {
        return mergeFrom((edu.ucf.student.jdavies.cnt5008.proto.Response)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(edu.ucf.student.jdavies.cnt5008.proto.Response other) {
      if (other == edu.ucf.student.jdavies.cnt5008.proto.Response.getDefaultInstance()) return this;
      if (other.hasHost()) {
        mergeHost(other.getHost());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      edu.ucf.student.jdavies.cnt5008.proto.Response parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (edu.ucf.student.jdavies.cnt5008.proto.Response) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private edu.ucf.student.jdavies.cnt5008.proto.HostId host_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        edu.ucf.student.jdavies.cnt5008.proto.HostId, edu.ucf.student.jdavies.cnt5008.proto.HostId.Builder, edu.ucf.student.jdavies.cnt5008.proto.HostIdOrBuilder> hostBuilder_;
    /**
     * <code>.proto.HostId host = 1;</code>
     */
    public boolean hasHost() {
      return hostBuilder_ != null || host_ != null;
    }
    /**
     * <code>.proto.HostId host = 1;</code>
     */
    public edu.ucf.student.jdavies.cnt5008.proto.HostId getHost() {
      if (hostBuilder_ == null) {
        return host_ == null ? edu.ucf.student.jdavies.cnt5008.proto.HostId.getDefaultInstance() : host_;
      } else {
        return hostBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.HostId host = 1;</code>
     */
    public Builder setHost(edu.ucf.student.jdavies.cnt5008.proto.HostId value) {
      if (hostBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        host_ = value;
        onChanged();
      } else {
        hostBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.proto.HostId host = 1;</code>
     */
    public Builder setHost(
        edu.ucf.student.jdavies.cnt5008.proto.HostId.Builder builderForValue) {
      if (hostBuilder_ == null) {
        host_ = builderForValue.build();
        onChanged();
      } else {
        hostBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.proto.HostId host = 1;</code>
     */
    public Builder mergeHost(edu.ucf.student.jdavies.cnt5008.proto.HostId value) {
      if (hostBuilder_ == null) {
        if (host_ != null) {
          host_ =
            edu.ucf.student.jdavies.cnt5008.proto.HostId.newBuilder(host_).mergeFrom(value).buildPartial();
        } else {
          host_ = value;
        }
        onChanged();
      } else {
        hostBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.proto.HostId host = 1;</code>
     */
    public Builder clearHost() {
      if (hostBuilder_ == null) {
        host_ = null;
        onChanged();
      } else {
        host_ = null;
        hostBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.proto.HostId host = 1;</code>
     */
    public edu.ucf.student.jdavies.cnt5008.proto.HostId.Builder getHostBuilder() {
      
      onChanged();
      return getHostFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.HostId host = 1;</code>
     */
    public edu.ucf.student.jdavies.cnt5008.proto.HostIdOrBuilder getHostOrBuilder() {
      if (hostBuilder_ != null) {
        return hostBuilder_.getMessageOrBuilder();
      } else {
        return host_ == null ?
            edu.ucf.student.jdavies.cnt5008.proto.HostId.getDefaultInstance() : host_;
      }
    }
    /**
     * <code>.proto.HostId host = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        edu.ucf.student.jdavies.cnt5008.proto.HostId, edu.ucf.student.jdavies.cnt5008.proto.HostId.Builder, edu.ucf.student.jdavies.cnt5008.proto.HostIdOrBuilder> 
        getHostFieldBuilder() {
      if (hostBuilder_ == null) {
        hostBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            edu.ucf.student.jdavies.cnt5008.proto.HostId, edu.ucf.student.jdavies.cnt5008.proto.HostId.Builder, edu.ucf.student.jdavies.cnt5008.proto.HostIdOrBuilder>(
                getHost(),
                getParentForChildren(),
                isClean());
        host_ = null;
      }
      return hostBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:proto.Response)
  }

  // @@protoc_insertion_point(class_scope:proto.Response)
  private static final edu.ucf.student.jdavies.cnt5008.proto.Response DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.ucf.student.jdavies.cnt5008.proto.Response();
  }

  public static edu.ucf.student.jdavies.cnt5008.proto.Response getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Response>
      PARSER = new com.google.protobuf.AbstractParser<Response>() {
    public Response parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Response> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Response> getParserForType() {
    return PARSER;
  }

  public edu.ucf.student.jdavies.cnt5008.proto.Response getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

