// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package edu.ucf.student.jdavies.cnt5008.proto;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.HostId host = 1;</code>
   */
  boolean hasHost();
  /**
   * <code>.proto.HostId host = 1;</code>
   */
  edu.ucf.student.jdavies.cnt5008.proto.HostId getHost();
  /**
   * <code>.proto.HostId host = 1;</code>
   */
  edu.ucf.student.jdavies.cnt5008.proto.HostIdOrBuilder getHostOrBuilder();
}
